# Generated by Django 2.0.2 on 2018-06-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(default=25, max_length=20, verbose_name='年龄'),
        ),
    ]
