# Generated by Django 2.0.2 on 2018-07-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20180629_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='tag',
            field=models.CharField(default='程氏集团', max_length=10, verbose_name='机构标签'),
        ),
    ]
